services:
  db:
    image: postgres:latest
    restart: always
    container_name: ria-db
    environment:
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: entity228
      POSTGRES_DB: ria
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  crawler:
    build: ./crawler
    container_name: ria-crawl

  server:
    build: ./api
    container_name: ria-server
    ports:
      - "9090:8080"

volumes:
  pgdata:
